export const LOGIN_ERROR = "LOGIN_ERROR";

export const ERROR = "ERROR";

export const FETCH_COMMENT_DATA_SUCCESS = "FETCH_COMMENT_DATA_SUCCESS";
export const ADD_COMMENT_DATA_SUCCESS = "ADD_COMMENT_DATA_SUCCESS";
export const RESET_COMMENT_DATA_SUCCESS = "RESET_COMMENT_DATA_SUCCESS";

export const ADD_COMMENT_DATA_PAGINATION = "ADD_COMMENT_DATA_PAGINATION";
export const FETCH_COMMENT_DATA_PAGINATION = "FETCH_COMMENT_DATA_PAGINATION";
export const RESET_COMMENT_DATA_PAGINATION = "RESET_COMMENT_DATA_PAGINATION";

export const ADD_TEXT = "ADD_TEXT";
export const REMOVE_TEXT = "REMOVE_TEXT";

export const IS_SHOW_SPINNER = "SHOW_SPINNER";

export const IS_SHOW_SUCESS_MODAL = "IS_SHOW_SUCESS_MODAL";

export const IS_SHOW_ERROR_MODAL = "IS_SHOW_ERROR_MODAL";

export const YOUTUBE_LINK = "YOUTUBE_LINK";

export const SEARCH_PROMPT_EDIT = "SEARCH_PROMPT_EDIT";
