data = [
    {
        'type': 2,
        'comment': 'Great video!',
        'positive_score': 40,
        'neutral_score': 97,
        'negative_score': 51,
    },
    {
        'type': 4,
        'comment': 'I learned so much!',
        'positive_score': 6,
        'neutral_score': 66,
        'negative_score': 8,
    },
    {
        'type': 4,
        'comment': 'This is my favorite channel!',
        'positive_score': 50,
        'neutral_score': 74,
        'negative_score': 62,
    },
    {
        'type': 2,
        'comment': 'Keep up the good work!',
        'positive_score': 68,
        'neutral_score': 25,
        'negative_score': 59,
    },
    {
        'type': 0,
        'comment': 'Awesome content!',
        'positive_score': 83,
        'neutral_score': 60,
        'negative_score': 37,
    },
    {
        'type': 0,
        'comment': 'I learned so much!',
        'positive_score': 35,
        'neutral_score': 22,
        'negative_score': 36,
    },
    {
        'type': 2,
        'comment': 'This is my favorite channel!',
        'positive_score': 55,
        'neutral_score': 53,
        'negative_score': 75,
    },
    {
        'type': 2,
        'comment': 'This is my favorite channel!',
        'positive_score': 95,
        'neutral_score': 82,
        'negative_score': 100,
    },
    {
        'type': 0,
        'comment': 'Awesome content!',
        'positive_score': 10,
        'neutral_score': 11,
        'negative_score': 32,
    },
    {
        'type': 4,
        'comment': 'Awesome content!',
        'positive_score': 82,
        'neutral_score': 80,
        'negative_score': 42,
    },
    {
        'type': 4,
        'comment': 'Great video!',
        'positive_score': 62,
        'neutral_score': 24,
        'negative_score': 96,
    },
    {
        'type': 0,
        'comment': 'Awesome content!',
        'positive_score': 62,
        'neutral_score': 66,
        'negative_score': 14,
    },
]

# Now 'datassss' is a list of dictionaries in Python