export const datassss = [
  { type: 4, comment: "I learned a lot!", score: 16 },
  { type: 4, comment: "Great video!", score: 25 },
  { type: 4, comment: "Great video!", score: 41 },
  { type: 2, comment: "So funny!", score: 33 },
  { type: 4, comment: "So funny!", score: 84 },
  { type: 0, comment: "Great video!", score: 46 },
  { type: 0, comment: "This deserves more views!", score: 80 },
  { type: 2, comment: "I can't stop watching!", score: 63 },
  { type: 2, comment: "You're the best!", score: 34 },
  { type: 0, comment: "I learned a lot!", score: 16 },
  { type: 4, comment: "I learned a lot!", score: 37 },
  { type: 0, comment: "This is amazing!", score: 31 },
  { type: 0, comment: "This deserves more views!", score: 65 },
  { type: 2, comment: "Keep up the good work!", score: 99 },
  { type: 4, comment: "So funny!", score: 41 },
  { type: 4, comment: "Great video!", score: 22 },
  { type: 0, comment: "You're the best!", score: 9 },
  { type: 2, comment: "Awesome content!", score: 8 },
  { type: 2, comment: "You're the best!", score: 14 },
  { type: 0, comment: "I'm subscribing!", score: 82 },
  { type: 4, comment: "Keep up the good work!", score: 74 },
  { type: 4, comment: "Great video!", score: 75 },
  { type: 4, comment: "This deserves more views!", score: 47 },
  { type: 4, comment: "This deserves more views!", score: 40 },
  { type: 0, comment: "I can't stop watching!", score: 57 },
  { type: 4, comment: "This deserves more views!", score: 81 },
  { type: 0, comment: "Great video!", score: 95 },
  { type: 0, comment: "Great video!", score: 49 },
  { type: 0, comment: "So funny!", score: 75 },
  { type: 4, comment: "I learned a lot!", score: 3 },
  { type: 2, comment: "I'm subscribing!", score: 89 },
  { type: 0, comment: "Keep up the good work!", score: 95 },
  { type: 4, comment: "Keep up the good work!", score: 18 },
  { type: 0, comment: "You're the best!", score: 18 },
  { type: 2, comment: "I learned a lot!", score: 91 },
  { type: 0, comment: "Awesome content!", score: 80 },
  { type: 0, comment: "I can't stop watching!", score: 91 },
  { type: 4, comment: "I can't stop watching!", score: 13 },
  { type: 4, comment: "I can't stop watching!", score: 90 },
  { type: 4, comment: "This is amazing!", score: 76 },
  { type: 4, comment: "Awesome content!", score: 97 },
  { type: 4, comment: "I can't stop watching!", score: 56 },
  { type: 0, comment: "Keep up the good work!", score: 29 },
  { type: 2, comment: "This deserves more views!", score: 92 },
  { type: 4, comment: "So funny!", score: 72 },
  { type: 2, comment: "So funny!", score: 44 },
  { type: 0, comment: "I'm subscribing!", score: 90 },
  { type: 2, comment: "This is amazing!", score: 46 },
  { type: 0, comment: "This deserves more views!", score: 29 },
  { type: 4, comment: "This is amazing!", score: 93 },
  { type: 0, comment: "I'm subscribing!", score: 32 },
  { type: 0, comment: "Keep up the good work!", score: 6 },
  { type: 4, comment: "You're the best!", score: 17 },
  { type: 0, comment: "This deserves more views!", score: 15 },
  { type: 2, comment: "You're the best!", score: 90 },
  { type: 4, comment: "I'm subscribing!", score: 38 },
  { type: 2, comment: "I can't stop watching!", score: 57 },
  { type: 0, comment: "You're the best!", score: 3 },
  { type: 4, comment: "Great video!", score: 3 },
  { type: 4, comment: "I'm subscribing!", score: 81 },
  { type: 0, comment: "This deserves more views!", score: 75 },
  { type: 2, comment: "You're the best!", score: 53 },
  { type: 4, comment: "So funny!", score: 72 },
  { type: 2, comment: "I learned a lot!", score: 82 },
  { type: 4, comment: "This is amazing!", score: 96 },
  { type: 2, comment: "This deserves more views!", score: 91 },
  { type: 2, comment: "Great video!", score: 19 },
  { type: 0, comment: "Keep up the good work!", score: 24 },
  { type: 2, comment: "Great video!", score: 90 },
  { type: 4, comment: "I'm subscribing!", score: 69 },
  { type: 0, comment: "I learned a lot!", score: 31 },
  { type: 2, comment: "You're the best!", score: 31 },
  { type: 2, comment: "Keep up the good work!", score: 23 },
  { type: 0, comment: "Great video!", score: 89 },
  { type: 2, comment: "You're the best!", score: 1 },
  { type: 0, comment: "This is amazing!", score: 31 },
  { type: 4, comment: "I'm subscribing!", score: 31 },
  { type: 0, comment: "I can't stop watching!", score: 61 },
  { type: 2, comment: "You're the best!", score: 11 },
  { type: 4, comment: "So funny!", score: 53 },
  { type: 0, comment: "Awesome content!", score: 63 },
  { type: 4, comment: "You're the best!", score: 33 },
  { type: 2, comment: "I can't stop watching!", score: 44 },
  { type: 2, comment: "Great video!", score: 65 },
  { type: 0, comment: "Great video!", score: 81 },
  { type: 2, comment: "This deserves more views!", score: 80 },
  { type: 4, comment: "I'm subscribing!", score: 40 },
  { type: 4, comment: "So funny!", score: 9 },
  { type: 2, comment: "I'm subscribing!", score: 56 },
  { type: 2, comment: "I'm subscribing!", score: 65 },
  { type: 0, comment: "You're the best!", score: 65 },
  { type: 4, comment: "This is amazing!", score: 16 },
  { type: 2, comment: "I'm subscribing!", score: 34 },
  { type: 2, comment: "Keep up the good work!", score: 76 },
  { type: 4, comment: "Great video!", score: 95 },
  { type: 0, comment: "This is amazing!", score: 64 },
  { type: 4, comment: "Keep up the good work!", score: 39 },
  { type: 2, comment: "I learned a lot!", score: 45 },
  { type: 2, comment: "This deserves more views!", score: 36 },
  { type: 4, comment: "Awesome content!", score: 70 },
  { type: 4, comment: "Awesome content!", score: 83 },
  { type: 2, comment: "Awesome content!", score: 24 },
  { type: 0, comment: "Keep up the good work!", score: 36 },
  { type: 2, comment: "This deserves more views!", score: 47 },
  { type: 0, comment: "I'm subscribing!", score: 17 },
  { type: 4, comment: "Great video!", score: 7 },
  { type: 2, comment: "This deserves more views!", score: 1 },
  { type: 4, comment: "I'm subscribing!", score: 32 },
  { type: 4, comment: "You're the best!", score: 31 },
  { type: 2, comment: "You're the best!", score: 60 },
  { type: 0, comment: "I'm subscribing!", score: 5 },
  { type: 0, comment: "This is amazing!", score: 44 },
  { type: 0, comment: "I can't stop watching!", score: 61 },
  { type: 4, comment: "This is amazing!", score: 71 },
  { type: 0, comment: "Keep up the good work!", score: 72 },
  { type: 2, comment: "I learned a lot!", score: 40 },
  { type: 4, comment: "Great video!", score: 12 },
  { type: 0, comment: "You're the best!", score: 14 },
  { type: 2, comment: "I learned a lot!", score: 91 },
  { type: 0, comment: "I'm subscribing!", score: 18 },
  { type: 0, comment: "So funny!", score: 24 },
  { type: 4, comment: "This deserves more views!", score: 34 },
  { type: 0, comment: "I can't stop watching!", score: 7 },
  { type: 2, comment: "You're the best!", score: 48 },
  { type: 4, comment: "So funny!", score: 24 },
  { type: 2, comment: "Keep up the good work!", score: 100 },
  { type: 4, comment: "You're the best!", score: 36 },
  { type: 0, comment: "I'm subscribing!", score: 95 },
  { type: 0, comment: "Keep up the good work!", score: 23 },
  { type: 4, comment: "This deserves more views!", score: 29 },
  { type: 4, comment: "This is amazing!", score: 32 },
  { type: 2, comment: "So funny!", score: 89 },
  { type: 4, comment: "This is amazing!", score: 52 },
  { type: 2, comment: "I learned a lot!", score: 67 },
  { type: 0, comment: "Awesome content!", score: 81 },
  { type: 4, comment: "I can't stop watching!", score: 95 },
  { type: 2, comment: "I can't stop watching!", score: 36 },
  { type: 4, comment: "You're the best!", score: 82 },
  { type: 4, comment: "Keep up the good work!", score: 4 },
  { type: 0, comment: "I'm subscribing!", score: 37 },
  { type: 2, comment: "Awesome content!", score: 0 },
  { type: 0, comment: "I can't stop watching!", score: 44 },
  { type: 4, comment: "So funny!", score: 59 },
  { type: 2, comment: "Great video!", score: 45 },
  { type: 0, comment: "This is amazing!", score: 68 },
  { type: 2, comment: "This is amazing!", score: 30 },
  { type: 2, comment: "This deserves more views!", score: 39 },
  { type: 0, comment: "Great video!", score: 72 },
  { type: 4, comment: "I'm subscribing!", score: 47 },
  { type: 4, comment: "Awesome content!", score: 12 },
  { type: 4, comment: "Keep up the good work!", score: 43 },
  { type: 4, comment: "Awesome content!", score: 94 },
  { type: 0, comment: "Great video!", score: 6 },
  { type: 2, comment: "This is amazing!", score: 8 },
  { type: 0, comment: "You're the best!", score: 68 },
  { type: 4, comment: "I'm subscribing!", score: 18 },
  { type: 2, comment: "This is amazing!", score: 31 },
  { type: 2, comment: "Awesome content!", score: 22 },
  { type: 2, comment: "This deserves more views!", score: 10 },
  { type: 0, comment: "Keep up the good work!", score: 7 },
  { type: 0, comment: "This is amazing!", score: 64 },
  { type: 4, comment: "I'm subscribing!", score: 57 },
  { type: 4, comment: "Great video!", score: 100 },
  { type: 2, comment: "I can't stop watching!", score: 42 },
  { type: 4, comment: "I can't stop watching!", score: 91 },
  { type: 0, comment: "I can't stop watching!", score: 40 },
  { type: 0, comment: "Great video!", score: 59 },
  { type: 2, comment: "You're the best!", score: 78 },
  { type: 2, comment: "I can't stop watching!", score: 75 },
  { type: 0, comment: "I learned a lot!", score: 96 },
  { type: 2, comment: "I learned a lot!", score: 76 },
  { type: 0, comment: "You're the best!", score: 22 },
  { type: 4, comment: "Awesome content!", score: 8 },
  { type: 4, comment: "Keep up the good work!", score: 99 },
  { type: 0, comment: "So funny!", score: 29 },
  { type: 4, comment: "Great video!", score: 0 },
  { type: 0, comment: "Awesome content!", score: 81 },
  { type: 2, comment: "I'm subscribing!", score: 1 },
  { type: 4, comment: "This deserves more views!", score: 93 },
  { type: 0, comment: "Awesome content!", score: 84 },
  { type: 4, comment: "Keep up the good work!", score: 40 },
  { type: 2, comment: "Keep up the good work!", score: 16 },
  { type: 0, comment: "I can't stop watching!", score: 0 },
  { type: 2, comment: "Great video!", score: 47 },
  { type: 0, comment: "Awesome content!", score: 54 },
  { type: 0, comment: "I can't stop watching!", score: 62 },
  { type: 2, comment: "Keep up the good work!", score: 5 },
  { type: 4, comment: "Great video!", score: 19 },
  { type: 2, comment: "I'm subscribing!", score: 72 },
  { type: 2, comment: "Keep up the good work!", score: 79 },
  { type: 4, comment: "Awesome content!", score: 50 },
  { type: 0, comment: "You're the best!", score: 54 },
  { type: 0, comment: "I can't stop watching!", score: 91 },
  { type: 2, comment: "I learned a lot!", score: 59 },
  { type: 2, comment: "So funny!", score: 96 },
  { type: 4, comment: "So funny!", score: 56 },
  { type: 0, comment: "Keep up the good work!", score: 76 },
  { type: 2, comment: "Awesome content!", score: 41 },
  { type: 0, comment: "This is amazing!", score: 74 },
  { type: 2, comment: "I learned a lot!", score: 84 },
  { type: 0, comment: "I can't stop watching!", score: 94 },
  { type: 0, comment: "So funny!", score: 77 },
  { type: 2, comment: "Keep up the good work!", score: 1 },
  { type: 2, comment: "Keep up the good work!", score: 98 },
  { type: 0, comment: "I'm subscribing!", score: 55 },
  { type: 0, comment: "This deserves more views!", score: 17 },
  { type: 4, comment: "Awesome content!", score: 67 },
  { type: 2, comment: "Great video!", score: 87 },
  { type: 4, comment: "Awesome content!", score: 36 },
  { type: 2, comment: "Great video!", score: 20 },
  { type: 2, comment: "This deserves more views!", score: 26 },
  { type: 4, comment: "Keep up the good work!", score: 80 },
  { type: 0, comment: "I can't stop watching!", score: 28 },
  { type: 4, comment: "I learned a lot!", score: 92 },
  { type: 0, comment: "Keep up the good work!", score: 19 },
  { type: 2, comment: "I'm subscribing!", score: 62 },
  { type: 0, comment: "This is amazing!", score: 4 },
  { type: 4, comment: "This deserves more views!", score: 67 },
  { type: 4, comment: "Great video!", score: 46 },
  { type: 0, comment: "I can't stop watching!", score: 58 },
  { type: 0, comment: "Great video!", score: 44 },
  { type: 2, comment: "I learned a lot!", score: 96 },
  { type: 4, comment: "Keep up the good work!", score: 92 },
  { type: 4, comment: "Keep up the good work!", score: 12 },
  { type: 4, comment: "This deserves more views!", score: 39 },
  { type: 2, comment: "I learned a lot!", score: 80 },
  { type: 0, comment: "So funny!", score: 55 },
  { type: 2, comment: "Great video!", score: 49 },
  { type: 4, comment: "Awesome content!", score: 32 },
  { type: 2, comment: "I learned a lot!", score: 78 },
  { type: 2, comment: "This deserves more views!", score: 96 },
  { type: 4, comment: "Keep up the good work!", score: 56 },
  { type: 2, comment: "Great video!", score: 15 },
  { type: 2, comment: "Great video!", score: 11 },
  { type: 2, comment: "Awesome content!", score: 51 },
  { type: 0, comment: "You're the best!", score: 34 },
  { type: 2, comment: "This is amazing!", score: 89 },
  { type: 2, comment: "This is amazing!", score: 8 },
  { type: 4, comment: "So funny!", score: 45 },
  { type: 0, comment: "Awesome content!", score: 80 },
  { type: 4, comment: "I learned a lot!", score: 69 },
  { type: 0, comment: "This deserves more views!", score: 16 },
  { type: 2, comment: "I learned a lot!", score: 6 },
  { type: 0, comment: "Keep up the good work!", score: 33 },
  { type: 0, comment: "So funny!", score: 40 },
  { type: 4, comment: "So funny!", score: 18 },
  { type: 4, comment: "This is amazing!", score: 35 },
  { type: 0, comment: "Awesome content!", score: 5 },
  { type: 2, comment: "I'm subscribing!", score: 35 },
  { type: 0, comment: "You're the best!", score: 82 },
  { type: 0, comment: "This is amazing!", score: 99 },
  { type: 4, comment: "Awesome content!", score: 62 },
  { type: 2, comment: "Keep up the good work!", score: 66 },
  { type: 2, comment: "This is amazing!", score: 96 },
  { type: 4, comment: "This deserves more views!", score: 99 },
  { type: 4, comment: "I'm subscribing!", score: 69 },
  { type: 0, comment: "This deserves more views!", score: 75 },
  { type: 2, comment: "I learned a lot!", score: 13 },
  { type: 0, comment: "This deserves more views!", score: 44 },
  { type: 2, comment: "I'm subscribing!", score: 50 },
  { type: 4, comment: "This is amazing!", score: 1 },
  { type: 0, comment: "You're the best!", score: 91 },
  { type: 2, comment: "I can't stop watching!", score: 14 },
  { type: 0, comment: "Keep up the good work!", score: 63 },
  { type: 2, comment: "Awesome content!", score: 2 },
  { type: 2, comment: "This deserves more views!", score: 38 },
  { type: 2, comment: "I learned a lot!", score: 92 },
  { type: 0, comment: "I'm subscribing!", score: 84 },
  { type: 4, comment: "I learned a lot!", score: 25 },
  { type: 2, comment: "I learned a lot!", score: 52 },
  { type: 2, comment: "So funny!", score: 97 },
  { type: 2, comment: "So funny!", score: 21 },
  { type: 4, comment: "Great video!", score: 82 },
  { type: 0, comment: "You're the best!", score: 64 },
  { type: 0, comment: "Keep up the good work!", score: 34 },
  { type: 4, comment: "This deserves more views!", score: 45 },
  { type: 2, comment: "So funny!", score: 23 },
  { type: 4, comment: "I'm subscribing!", score: 6 },
  { type: 2, comment: "I'm subscribing!", score: 18 },
  { type: 2, comment: "I learned a lot!", score: 20 },
  { type: 0, comment: "I learned a lot!", score: 45 },
  { type: 2, comment: "I learned a lot!", score: 98 },
  { type: 4, comment: "Great video!", score: 66 },
  { type: 4, comment: "You're the best!", score: 55 },
  { type: 2, comment: "I learned a lot!", score: 68 },
  { type: 2, comment: "You're the best!", score: 33 },
  { type: 0, comment: "This is amazing!", score: 37 },
  { type: 0, comment: "You're the best!", score: 78 },
  { type: 4, comment: "Awesome content!", score: 89 },
  { type: 2, comment: "You're the best!", score: 83 },
  { type: 4, comment: "I'm subscribing!", score: 73 },
  { type: 4, comment: "This deserves more views!", score: 12 },
  { type: 2, comment: "Awesome content!", score: 54 },
  { type: 0, comment: "This deserves more views!", score: 19 },
  { type: 2, comment: "I'm subscribing!", score: 47 },
  { type: 0, comment: "I can't stop watching!", score: 93 },
  { type: 0, comment: "So funny!", score: 87 },
  { type: 0, comment: "Keep up the good work!", score: 47 },
  { type: 4, comment: "Awesome content!", score: 67 },
  { type: 4, comment: "Great video!", score: 34 },
  { type: 2, comment: "This is amazing!", score: 1 },
  { type: 4, comment: "Keep up the good work!", score: 4 },
  { type: 2, comment: "Awesome content!", score: 89 },
  { type: 0, comment: "Awesome content!", score: 40 },
  { type: 2, comment: "Keep up the good work!", score: 45 },
  { type: 2, comment: "Great video!", score: 2 },
  { type: 4, comment: "Keep up the good work!", score: 2 },
  { type: 4, comment: "This deserves more views!", score: 56 },
  { type: 4, comment: "This is amazing!", score: 90 },
  { type: 2, comment: "You're the best!", score: 40 },
  { type: 2, comment: "I can't stop watching!", score: 35 },
  { type: 4, comment: "This deserves more views!", score: 97 },
  { type: 2, comment: "Great video!", score: 39 },
  { type: 0, comment: "I learned a lot!", score: 3 },
  { type: 4, comment: "I learned a lot!", score: 53 },
  { type: 0, comment: "Awesome content!", score: 81 },
  { type: 4, comment: "This is amazing!", score: 56 },
  { type: 4, comment: "You're the best!", score: 82 },
  { type: 4, comment: "Awesome content!", score: 38 },
  { type: 4, comment: "Keep up the good work!", score: 28 },
  { type: 4, comment: "I'm subscribing!", score: 41 },
  { type: 2, comment: "You're the best!", score: 76 },
  { type: 2, comment: "So funny!", score: 85 },
  { type: 2, comment: "So funny!", score: 95 },
  { type: 4, comment: "I can't stop watching!", score: 68 },
  { type: 2, comment: "I'm subscribing!", score: 8 },
  { type: 2, comment: "Great video!", score: 86 },
  { type: 2, comment: "Awesome content!", score: 66 },
  { type: 2, comment: "Great video!", score: 97 },
  { type: 0, comment: "I'm subscribing!", score: 26 },
  { type: 0, comment: "This is amazing!", score: 47 },
  { type: 2, comment: "So funny!", score: 87 },
  { type: 2, comment: "This is amazing!", score: 96 },
  { type: 0, comment: "This is amazing!", score: 13 },
  { type: 4, comment: "Keep up the good work!", score: 3 },
  { type: 2, comment: "Keep up the good work!", score: 32 },
  { type: 0, comment: "This is amazing!", score: 30 },
  { type: 0, comment: "Keep up the good work!", score: 22 },
  { type: 2, comment: "I can't stop watching!", score: 41 },
  { type: 2, comment: "So funny!", score: 21 },
  { type: 4, comment: "I can't stop watching!", score: 19 },
  { type: 0, comment: "So funny!", score: 39 },
  { type: 2, comment: "I'm subscribing!", score: 15 },
  { type: 2, comment: "Keep up the good work!", score: 4 },
  { type: 4, comment: "Awesome content!", score: 65 },
  { type: 4, comment: "I learned a lot!", score: 84 },
  { type: 0, comment: "So funny!", score: 63 },
  { type: 0, comment: "You're the best!", score: 64 },
  { type: 4, comment: "Great video!", score: 37 },
  { type: 0, comment: "I learned a lot!", score: 86 },
  { type: 0, comment: "I can't stop watching!", score: 77 },
  { type: 2, comment: "Keep up the good work!", score: 48 },
  { type: 0, comment: "I'm subscribing!", score: 67 },
  { type: 2, comment: "This deserves more views!", score: 6 },
  { type: 2, comment: "Great video!", score: 53 },
  { type: 4, comment: "Awesome content!", score: 11 },
  { type: 4, comment: "I'm subscribing!", score: 44 },
  { type: 0, comment: "You're the best!", score: 60 },
  { type: 0, comment: "This deserves more views!", score: 99 },
  { type: 2, comment: "Keep up the good work!", score: 97 },
  { type: 4, comment: "You're the best!", score: 89 },
  { type: 0, comment: "This is amazing!", score: 47 },
  { type: 0, comment: "So funny!", score: 30 },
  { type: 0, comment: "I can't stop watching!", score: 13 },
  { type: 4, comment: "I can't stop watching!", score: 52 },
  { type: 2, comment: "I can't stop watching!", score: 27 },
  { type: 4, comment: "You're the best!", score: 19 },
  { type: 4, comment: "Keep up the good work!", score: 86 },
  { type: 2, comment: "You're the best!", score: 93 },
  { type: 0, comment: "You're the best!", score: 63 },
  { type: 0, comment: "This deserves more views!", score: 91 },
  { type: 2, comment: "This is amazing!", score: 39 },
  { type: 2, comment: "So funny!", score: 49 },
  { type: 4, comment: "I learned a lot!", score: 53 },
  { type: 0, comment: "Keep up the good work!", score: 44 },
  { type: 0, comment: "You're the best!", score: 16 },
  { type: 4, comment: "You're the best!", score: 4 },
  { type: 2, comment: "Keep up the good work!", score: 27 },
  { type: 4, comment: "I learned a lot!", score: 3 },
  { type: 0, comment: "I can't stop watching!", score: 24 },
  { type: 2, comment: "I learned a lot!", score: 53 },
  { type: 0, comment: "I'm subscribing!", score: 79 },
  { type: 0, comment: "Keep up the good work!", score: 45 },
  { type: 2, comment: "You're the best!", score: 55 },
  { type: 4, comment: "Awesome content!", score: 24 },
  { type: 0, comment: "You're the best!", score: 14 },
  { type: 0, comment: "Awesome content!", score: 66 },
  { type: 4, comment: "I can't stop watching!", score: 91 },
  { type: 2, comment: "I'm subscribing!", score: 73 },
  { type: 4, comment: "You're the best!", score: 77 },
  { type: 4, comment: "This is amazing!", score: 19 },
  { type: 2, comment: "Great video!", score: 27 },
  { type: 4, comment: "Awesome content!", score: 33 },
  { type: 0, comment: "This deserves more views!", score: 98 },
  { type: 4, comment: "This deserves more views!", score: 64 },
  { type: 2, comment: "Great video!", score: 76 },
  { type: 2, comment: "This is amazing!", score: 95 },
  { type: 2, comment: "This is amazing!", score: 51 },
  { type: 2, comment: "This is amazing!", score: 59 },
  { type: 4, comment: "Keep up the good work!", score: 21 },
  { type: 4, comment: "This is amazing!", score: 29 },
  { type: 4, comment: "Great video!", score: 44 },
  { type: 0, comment: "I'm subscribing!", score: 13 },
  { type: 4, comment: "This is amazing!", score: 63 },
  { type: 4, comment: "You're the best!", score: 59 },
  { type: 0, comment: "I'm subscribing!", score: 41 },
  { type: 2, comment: "Keep up the good work!", score: 18 },
  { type: 0, comment: "I can't stop watching!", score: 48 },
  { type: 4, comment: "I learned a lot!", score: 81 },
  { type: 2, comment: "I learned a lot!", score: 94 },
  { type: 2, comment: "Great video!", score: 91 },
  { type: 4, comment: "I can't stop watching!", score: 3 },
  { type: 0, comment: "So funny!", score: 3 },
  { type: 4, comment: "Keep up the good work!", score: 28 },
  { type: 2, comment: "Awesome content!", score: 39 },
  { type: 4, comment: "This is amazing!", score: 68 },
  { type: 0, comment: "You're the best!", score: 81 },
  { type: 0, comment: "So funny!", score: 20 },
  { type: 0, comment: "Great video!", score: 74 },
  { type: 0, comment: "Awesome content!", score: 3 },
  { type: 0, comment: "I learned a lot!", score: 85 },
  { type: 0, comment: "So funny!", score: 43 },
  { type: 2, comment: "Keep up the good work!", score: 78 },
  { type: 2, comment: "Keep up the good work!", score: 26 },
  { type: 2, comment: "I'm subscribing!", score: 64 },
  { type: 0, comment: "You're the best!", score: 36 },
  { type: 2, comment: "Keep up the good work!", score: 13 },
  { type: 2, comment: "I'm subscribing!", score: 80 },
  { type: 0, comment: "Keep up the good work!", score: 36 },
  { type: 4, comment: "Great video!", score: 59 },
  { type: 2, comment: "This is amazing!", score: 16 },
  { type: 4, comment: "I learned a lot!", score: 10 },
  { type: 2, comment: "So funny!", score: 51 },
  { type: 2, comment: "Keep up the good work!", score: 35 },
  { type: 2, comment: "I learned a lot!", score: 67 },
  { type: 0, comment: "Keep up the good work!", score: 83 },
  { type: 4, comment: "Awesome content!", score: 17 },
  { type: 0, comment: "I learned a lot!", score: 99 },
  { type: 2, comment: "You're the best!", score: 83 },
  { type: 4, comment: "So funny!", score: 39 },
  { type: 4, comment: "So funny!", score: 10 },
  { type: 4, comment: "So funny!", score: 78 },
  { type: 4, comment: "This deserves more views!", score: 70 },
  { type: 4, comment: "This deserves more views!", score: 28 },
  { type: 2, comment: "I learned a lot!", score: 40 },
  { type: 4, comment: "This is amazing!", score: 69 },
  { type: 2, comment: "Keep up the good work!", score: 12 },
  { type: 4, comment: "I can't stop watching!", score: 31 },
  { type: 2, comment: "This deserves more views!", score: 62 },
  { type: 4, comment: "Awesome content!", score: 78 },
  { type: 0, comment: "You're the best!", score: 57 },
  { type: 4, comment: "Keep up the good work!", score: 26 },
  { type: 0, comment: "You're the best!", score: 41 },
  { type: 4, comment: "Great video!", score: 38 },
  { type: 0, comment: "Keep up the good work!", score: 51 },
  { type: 2, comment: "This is amazing!", score: 18 },
  { type: 2, comment: "Awesome content!", score: 14 },
  { type: 2, comment: "This deserves more views!", score: 51 },
  { type: 2, comment: "This is amazing!", score: 32 },
  { type: 0, comment: "I'm subscribing!", score: 32 },
  { type: 2, comment: "I learned a lot!", score: 30 },
  { type: 2, comment: "Keep up the good work!", score: 2 },
  { type: 0, comment: "This is amazing!", score: 75 },
  { type: 4, comment: "So funny!", score: 25 },
  { type: 4, comment: "You're the best!", score: 30 },
  { type: 4, comment: "I can't stop watching!", score: 30 },
  { type: 0, comment: "I'm subscribing!", score: 91 },
  { type: 0, comment: "Great video!", score: 82 },
  { type: 0, comment: "I'm subscribing!", score: 78 },
  { type: 4, comment: "So funny!", score: 44 },
  { type: 4, comment: "I'm subscribing!", score: 56 },
  { type: 4, comment: "I'm subscribing!", score: 88 },
  { type: 2, comment: "I learned a lot!", score: 47 },
  { type: 2, comment: "I can't stop watching!", score: 38 },
  { type: 4, comment: "Keep up the good work!", score: 81 },
  { type: 0, comment: "I learned a lot!", score: 56 },
  { type: 2, comment: "You're the best!", score: 25 },
  { type: 4, comment: "You're the best!", score: 49 },
  { type: 4, comment: "Keep up the good work!", score: 11 },
  { type: 4, comment: "So funny!", score: 48 },
  { type: 0, comment: "You're the best!", score: 9 },
  { type: 2, comment: "I learned a lot!", score: 47 },
  { type: 2, comment: "I can't stop watching!", score: 25 },
  { type: 4, comment: "Keep up the good work!", score: 12 },
  { type: 4, comment: "You're the best!", score: 90 },
  { type: 2, comment: "This is amazing!", score: 39 },
  { type: 2, comment: "I can't stop watching!", score: 1 },
  { type: 0, comment: "I learned a lot!", score: 24 },
  { type: 0, comment: "I'm subscribing!", score: 74 },
  { type: 0, comment: "Keep up the good work!", score: 27 },
  { type: 4, comment: "I'm subscribing!", score: 90 },
  { type: 4, comment: "I learned a lot!", score: 22 },
  { type: 2, comment: "Great video!", score: 98 },
  { type: 2, comment: "This deserves more views!", score: 33 },
  { type: 2, comment: "I'm subscribing!", score: 64 },
  { type: 4, comment: "I'm subscribing!", score: 61 },
  { type: 4, comment: "Keep up the good work!", score: 69 },
  { type: 0, comment: "I'm subscribing!", score: 55 },
  { type: 0, comment: "So funny!", score: 71 },
  { type: 4, comment: "Great video!", score: 36 },
  { type: 4, comment: "I learned a lot!", score: 16 },
  { type: 4, comment: "You're the best!", score: 46 },
  { type: 0, comment: "This deserves more views!", score: 82 },
  { type: 4, comment: "I'm subscribing!", score: 66 },
  { type: 0, comment: "This is amazing!", score: 67 },
  { type: 4, comment: "Great video!", score: 83 },
  { type: 2, comment: "I learned a lot!", score: 57 },
  { type: 4, comment: "I'm subscribing!", score: 16 },
  { type: 2, comment: "You're the best!", score: 26 },
  { type: 2, comment: "You're the best!", score: 65 },
  { type: 4, comment: "Keep up the good work!", score: 19 },
  { type: 0, comment: "I can't stop watching!", score: 70 },
  { type: 2, comment: "I'm subscribing!", score: 18 },
  { type: 4, comment: "So funny!", score: 52 },
  { type: 0, comment: "I can't stop watching!", score: 80 },
  { type: 2, comment: "So funny!", score: 6 },
  { type: 0, comment: "Awesome content!", score: 84 },
  { type: 2, comment: "Keep up the good work!", score: 90 },
  { type: 4, comment: "Great video!", score: 15 },
  { type: 4, comment: "I learned a lot!", score: 85 },
  { type: 4, comment: "Great video!", score: 91 },
  { type: 4, comment: "So funny!", score: 100 },
  { type: 0, comment: "I learned a lot!", score: 34 },
  { type: 2, comment: "This is amazing!", score: 77 },
  { type: 2, comment: "This is amazing!", score: 21 },
  { type: 4, comment: "I can't stop watching!", score: 60 },
  { type: 4, comment: "Great video!", score: 0 },
  { type: 2, comment: "This is amazing!", score: 6 },
  { type: 4, comment: "This is amazing!", score: 98 },
  { type: 2, comment: "This is amazing!", score: 77 },
  { type: 0, comment: "I can't stop watching!", score: 76 },
  { type: 0, comment: "I'm subscribing!", score: 17 },
  { type: 0, comment: "So funny!", score: 51 },
  { type: 4, comment: "Keep up the good work!", score: 69 },
  { type: 2, comment: "I can't stop watching!", score: 11 },
  { type: 0, comment: "Keep up the good work!", score: 2 },
  { type: 0, comment: "This deserves more views!", score: 2 },
  { type: 2, comment: "Awesome content!", score: 29 },
  { type: 4, comment: "I can't stop watching!", score: 26 },
  { type: 2, comment: "Awesome content!", score: 45 },
  { type: 2, comment: "So funny!", score: 78 },
  { type: 0, comment: "Keep up the good work!", score: 31 },
  { type: 2, comment: "This is amazing!", score: 34 },
  { type: 4, comment: "Keep up the good work!", score: 18 },
  { type: 0, comment: "I can't stop watching!", score: 28 },
  { type: 4, comment: "You're the best!", score: 93 },
  { type: 4, comment: "So funny!", score: 52 },
  { type: 2, comment: "Keep up the good work!", score: 52 },
  { type: 0, comment: "I'm subscribing!", score: 52 },
  { type: 0, comment: "You're the best!", score: 73 },
  { type: 2, comment: "Keep up the good work!", score: 40 },
  { type: 0, comment: "You're the best!", score: 67 },
  { type: 4, comment: "So funny!", score: 5 },
  { type: 4, comment: "I learned a lot!", score: 25 },
  { type: 2, comment: "You're the best!", score: 96 },
  { type: 0, comment: "You're the best!", score: 38 },
  { type: 2, comment: "You're the best!", score: 2 },
  { type: 2, comment: "So funny!", score: 74 },
  { type: 0, comment: "Awesome content!", score: 96 },
  { type: 0, comment: "Awesome content!", score: 83 },
  { type: 0, comment: "I can't stop watching!", score: 10 },
  { type: 2, comment: "I can't stop watching!", score: 93 },
  { type: 2, comment: "Great video!", score: 30 },
  { type: 4, comment: "You're the best!", score: 98 },
  { type: 0, comment: "Keep up the good work!", score: 66 },
  { type: 2, comment: "So funny!", score: 78 },
  { type: 4, comment: "I learned a lot!", score: 6 },
  { type: 0, comment: "So funny!", score: 100 },
  { type: 2, comment: "So funny!", score: 56 },
  { type: 0, comment: "This deserves more views!", score: 84 },
  { type: 0, comment: "Great video!", score: 42 },
  { type: 4, comment: "You're the best!", score: 48 },
  { type: 2, comment: "I can't stop watching!", score: 91 },
  { type: 0, comment: "This is amazing!", score: 42 },
  { type: 0, comment: "I'm subscribing!", score: 70 },
  { type: 4, comment: "So funny!", score: 18 },
  { type: 2, comment: "I can't stop watching!", score: 98 },
  { type: 2, comment: "This deserves more views!", score: 6 },
  { type: 2, comment: "This is amazing!", score: 97 },
  { type: 2, comment: "I learned a lot!", score: 91 },
  { type: 2, comment: "I learned a lot!", score: 74 },
  { type: 2, comment: "I learned a lot!", score: 26 },
  { type: 4, comment: "I'm subscribing!", score: 10 },
  { type: 2, comment: "You're the best!", score: 56 },
  { type: 4, comment: "This is amazing!", score: 41 },
  { type: 4, comment: "This deserves more views!", score: 93 },
  { type: 0, comment: "You're the best!", score: 48 },
  { type: 0, comment: "I'm subscribing!", score: 94 },
  { type: 2, comment: "Awesome content!", score: 57 },
  { type: 4, comment: "Awesome content!", score: 57 },
  { type: 2, comment: "I'm subscribing!", score: 94 },
  { type: 0, comment: "Great video!", score: 95 },
  { type: 4, comment: "I can't stop watching!", score: 33 },
  { type: 2, comment: "So funny!", score: 49 },
  { type: 2, comment: "So funny!", score: 49 },
  { type: 0, comment: "I can't stop watching!", score: 0 },
  { type: 4, comment: "I learned a lot!", score: 13 },
  { type: 2, comment: "You're the best!", score: 89 },
  { type: 0, comment: "Awesome content!", score: 26 },
  { type: 4, comment: "This is amazing!", score: 99 },
  { type: 4, comment: "This is amazing!", score: 33 },
  { type: 0, comment: "Keep up the good work!", score: 28 },
  { type: 2, comment: "I learned a lot!", score: 28 },
  { type: 0, comment: "I learned a lot!", score: 87 },
  { type: 4, comment: "You're the best!", score: 86 },
  { type: 2, comment: "You're the best!", score: 96 },
  { type: 4, comment: "I'm subscribing!", score: 37 },
  { type: 0, comment: "Great video!", score: 66 },
  { type: 2, comment: "So funny!", score: 78 },
  { type: 2, comment: "I'm subscribing!", score: 12 },
  { type: 4, comment: "So funny!", score: 59 },
  { type: 0, comment: "I can't stop watching!", score: 15 },
  { type: 2, comment: "Great video!", score: 31 },
  { type: 0, comment: "I'm subscribing!", score: 41 },
  { type: 4, comment: "Awesome content!", score: 100 },
  { type: 2, comment: "This deserves more views!", score: 73 },
  { type: 4, comment: "I can't stop watching!", score: 53 },
  { type: 4, comment: "Keep up the good work!", score: 62 },
  { type: 2, comment: "This is amazing!", score: 40 },
  { type: 0, comment: "I'm subscribing!", score: 0 },
  { type: 2, comment: "Awesome content!", score: 12 },
  { type: 0, comment: "I learned a lot!", score: 89 },
  { type: 2, comment: "Great video!", score: 79 },
  { type: 4, comment: "Awesome content!", score: 13 },
  { type: 2, comment: "I learned a lot!", score: 15 },
  { type: 0, comment: "Keep up the good work!", score: 44 },
  { type: 0, comment: "Keep up the good work!", score: 87 },
  { type: 2, comment: "Great video!", score: 69 },
  { type: 4, comment: "Keep up the good work!", score: 54 },
  { type: 2, comment: "I can't stop watching!", score: 89 },
  { type: 2, comment: "This is amazing!", score: 69 },
  { type: 2, comment: "This deserves more views!", score: 78 },
  { type: 2, comment: "This is amazing!", score: 32 },
  { type: 2, comment: "So funny!", score: 78 },
  { type: 2, comment: "Awesome content!", score: 40 },
  { type: 0, comment: "Awesome content!", score: 86 },
  { type: 0, comment: "Great video!", score: 42 },
  { type: 4, comment: "I can't stop watching!", score: 26 },
  { type: 2, comment: "I can't stop watching!", score: 94 },
  { type: 2, comment: "I learned a lot!", score: 72 },
  { type: 4, comment: "Great video!", score: 6 },
  { type: 0, comment: "I'm subscribing!", score: 80 },
  { type: 0, comment: "I learned a lot!", score: 58 },
  { type: 2, comment: "Great video!", score: 42 },
  { type: 4, comment: "Keep up the good work!", score: 75 },
  { type: 4, comment: "I learned a lot!", score: 58 },
  { type: 2, comment: "Great video!", score: 41 },
  { type: 4, comment: "I can't stop watching!", score: 69 },
  { type: 4, comment: "Awesome content!", score: 7 },
  { type: 4, comment: "Awesome content!", score: 8 },
  { type: 0, comment: "I can't stop watching!", score: 80 },
  { type: 4, comment: "Keep up the good work!", score: 54 },
  { type: 2, comment: "Great video!", score: 78 },
  { type: 4, comment: "I can't stop watching!", score: 92 },
  { type: 0, comment: "I can't stop watching!", score: 2 },
  { type: 0, comment: "I learned a lot!", score: 78 },
  { type: 4, comment: "Great video!", score: 50 },
  { type: 4, comment: "So funny!", score: 98 },
  { type: 0, comment: "Awesome content!", score: 60 },
  { type: 4, comment: "This deserves more views!", score: 11 },
  { type: 2, comment: "I can't stop watching!", score: 31 },
  { type: 2, comment: "So funny!", score: 50 },
  { type: 0, comment: "This deserves more views!", score: 8 },
  { type: 4, comment: "I learned a lot!", score: 93 },
  { type: 4, comment: "Keep up the good work!", score: 74 },
  { type: 4, comment: "I learned a lot!", score: 58 },
  { type: 2, comment: "I'm subscribing!", score: 27 },
  { type: 0, comment: "I learned a lot!", score: 51 },
  { type: 4, comment: "Keep up the good work!", score: 0 },
  { type: 4, comment: "I'm subscribing!", score: 80 },
  { type: 2, comment: "I can't stop watching!", score: 91 },
  { type: 4, comment: "I can't stop watching!", score: 78 },
  { type: 0, comment: "Great video!", score: 36 },
  { type: 0, comment: "So funny!", score: 84 },
  { type: 4, comment: "So funny!", score: 31 },
  { type: 2, comment: "I can't stop watching!", score: 27 },
  { type: 2, comment: "Awesome content!", score: 62 },
  { type: 0, comment: "This is amazing!", score: 98 },
  { type: 2, comment: "Keep up the good work!", score: 93 },
  { type: 4, comment: "You're the best!", score: 10 },
  { type: 2, comment: "This deserves more views!", score: 90 },
  { type: 0, comment: "I'm subscribing!", score: 39 },
  { type: 0, comment: "I can't stop watching!", score: 44 },
  { type: 4, comment: "This is amazing!", score: 97 },
  { type: 0, comment: "This is amazing!", score: 35 },
  { type: 2, comment: "Keep up the good work!", score: 91 },
  { type: 4, comment: "So funny!", score: 24 },
  { type: 2, comment: "So funny!", score: 9 },
  { type: 4, comment: "Keep up the good work!", score: 64 },
  { type: 0, comment: "I'm subscribing!", score: 26 },
  { type: 2, comment: "Keep up the good work!", score: 12 },
  { type: 2, comment: "I learned a lot!", score: 61 },
  { type: 4, comment: "Great video!", score: 64 },
  { type: 0, comment: "Awesome content!", score: 63 },
  { type: 0, comment: "You're the best!", score: 68 },
  { type: 2, comment: "This deserves more views!", score: 7 },
  { type: 2, comment: "Awesome content!", score: 94 },
  { type: 2, comment: "This is amazing!", score: 83 },
  { type: 0, comment: "Keep up the good work!", score: 64 },
  { type: 4, comment: "This deserves more views!", score: 64 },
  { type: 4, comment: "This is amazing!", score: 89 },
  { type: 2, comment: "Great video!", score: 32 },
  { type: 0, comment: "I can't stop watching!", score: 78 },
  { type: 2, comment: "So funny!", score: 42 },
  { type: 2, comment: "Awesome content!", score: 71 },
  { type: 0, comment: "I'm subscribing!", score: 93 },
  { type: 0, comment: "I can't stop watching!", score: 82 },
  { type: 2, comment: "This deserves more views!", score: 73 },
  { type: 2, comment: "I can't stop watching!", score: 94 },
  { type: 4, comment: "Keep up the good work!", score: 76 },
  { type: 2, comment: "I learned a lot!", score: 89 },
  { type: 4, comment: "I can't stop watching!", score: 76 },
  { type: 2, comment: "I learned a lot!", score: 52 },
  { type: 2, comment: "You're the best!", score: 58 },
  { type: 2, comment: "So funny!", score: 76 },
  { type: 2, comment: "I'm subscribing!", score: 64 },
  { type: 0, comment: "You're the best!", score: 59 },
  { type: 4, comment: "I can't stop watching!", score: 44 },
  { type: 0, comment: "Keep up the good work!", score: 13 },
  { type: 2, comment: "This deserves more views!", score: 24 },
  { type: 4, comment: "You're the best!", score: 10 },
  { type: 2, comment: "So funny!", score: 60 },
  { type: 2, comment: "This deserves more views!", score: 77 },
  { type: 0, comment: "This is amazing!", score: 8 },
  { type: 2, comment: "You're the best!", score: 30 },
  { type: 2, comment: "Awesome content!", score: 0 },
  { type: 4, comment: "This deserves more views!", score: 65 },
  { type: 2, comment: "Great video!", score: 94 },
  { type: 4, comment: "Awesome content!", score: 56 },
  { type: 2, comment: "I'm subscribing!", score: 94 },
  { type: 4, comment: "I'm subscribing!", score: 13 },
  { type: 0, comment: "You're the best!", score: 86 },
  { type: 4, comment: "I can't stop watching!", score: 56 },
  { type: 2, comment: "Keep up the good work!", score: 47 },
  { type: 0, comment: "So funny!", score: 76 },
  { type: 0, comment: "Awesome content!", score: 64 },
  { type: 2, comment: "I learned a lot!", score: 87 },
  { type: 4, comment: "You're the best!", score: 14 },
  { type: 4, comment: "I can't stop watching!", score: 100 },
  { type: 4, comment: "So funny!", score: 58 },
  { type: 4, comment: "I'm subscribing!", score: 92 },
  { type: 0, comment: "You're the best!", score: 28 },
  { type: 4, comment: "You're the best!", score: 0 },
  { type: 2, comment: "I'm subscribing!", score: 6 },
  { type: 2, comment: "So funny!", score: 50 },
  { type: 2, comment: "So funny!", score: 11 },
  { type: 2, comment: "I'm subscribing!", score: 60 },
  { type: 2, comment: "I learned a lot!", score: 24 },
  { type: 2, comment: "I'm subscribing!", score: 81 },
  { type: 0, comment: "This is amazing!", score: 13 },
  { type: 4, comment: "I'm subscribing!", score: 92 },
  { type: 4, comment: "I learned a lot!", score: 8 },
  { type: 2, comment: "Great video!", score: 19 },
  { type: 4, comment: "So funny!", score: 14 },
  { type: 4, comment: "This deserves more views!", score: 57 },
  { type: 4, comment: "Keep up the good work!", score: 8 },
  { type: 4, comment: "This is amazing!", score: 53 },
  { type: 0, comment: "So funny!", score: 22 },
  { type: 2, comment: "So funny!", score: 81 },
  { type: 2, comment: "So funny!", score: 9 },
  { type: 2, comment: "Awesome content!", score: 64 },
  { type: 2, comment: "So funny!", score: 51 },
  { type: 0, comment: "Great video!", score: 85 },
  { type: 4, comment: "I learned a lot!", score: 3 },
  { type: 4, comment: "Great video!", score: 0 },
  { type: 4, comment: "I learned a lot!", score: 2 },
  { type: 2, comment: "You're the best!", score: 48 },
  { type: 0, comment: "Awesome content!", score: 65 },
  { type: 0, comment: "I learned a lot!", score: 58 },
  { type: 0, comment: "I learned a lot!", score: 33 },
  { type: 2, comment: "I'm subscribing!", score: 94 },
  { type: 2, comment: "Great video!", score: 62 },
  { type: 2, comment: "This is amazing!", score: 29 },
  { type: 2, comment: "Great video!", score: 67 },
  { type: 4, comment: "I can't stop watching!", score: 90 },
  { type: 0, comment: "I'm subscribing!", score: 46 },
  { type: 2, comment: "This is amazing!", score: 8 },
  { type: 2, comment: "Keep up the good work!", score: 3 },
  { type: 4, comment: "I'm subscribing!", score: 33 },
  { type: 4, comment: "Great video!", score: 46 },
  { type: 2, comment: "This is amazing!", score: 57 },
  { type: 0, comment: "Keep up the good work!", score: 53 },
  { type: 0, comment: "I learned a lot!", score: 11 },
  { type: 0, comment: "Keep up the good work!", score: 33 },
  { type: 4, comment: "I can't stop watching!", score: 4 },
  { type: 4, comment: "I learned a lot!", score: 79 },
  { type: 4, comment: "I can't stop watching!", score: 76 },
  { type: 0, comment: "I'm subscribing!", score: 24 },
  { type: 2, comment: "Great video!", score: 39 },
  { type: 4, comment: "You're the best!", score: 80 },
  { type: 4, comment: "I'm subscribing!", score: 47 },
  { type: 0, comment: "So funny!", score: 25 },
  { type: 2, comment: "I can't stop watching!", score: 34 },
  { type: 2, comment: "You're the best!", score: 100 },
  { type: 4, comment: "I can't stop watching!", score: 58 },
  { type: 2, comment: "Great video!", score: 83 },
  { type: 4, comment: "Keep up the good work!", score: 11 },
  { type: 2, comment: "You're the best!", score: 6 },
  { type: 0, comment: "Awesome content!", score: 7 },
  { type: 4, comment: "You're the best!", score: 42 },
  { type: 4, comment: "Great video!", score: 77 },
  { type: 2, comment: "I can't stop watching!", score: 34 },
  { type: 2, comment: "So funny!", score: 63 },
  { type: 2, comment: "This deserves more views!", score: 47 },
  { type: 4, comment: "Keep up the good work!", score: 18 },
  { type: 2, comment: "I'm subscribing!", score: 82 },
  { type: 2, comment: "This is amazing!", score: 81 },
  { type: 0, comment: "I learned a lot!", score: 88 },
  { type: 4, comment: "I'm subscribing!", score: 64 },
  { type: 2, comment: "Awesome content!", score: 9 },
  { type: 0, comment: "Keep up the good work!", score: 20 },
  { type: 4, comment: "So funny!", score: 29 },
  { type: 0, comment: "I can't stop watching!", score: 79 },
  { type: 4, comment: "You're the best!", score: 71 },
  { type: 0, comment: "I learned a lot!", score: 43 },
  { type: 2, comment: "This is amazing!", score: 81 },
  { type: 4, comment: "This is amazing!", score: 54 },
  { type: 0, comment: "You're the best!", score: 77 },
  { type: 4, comment: "I learned a lot!", score: 53 },
  { type: 0, comment: "Awesome content!", score: 97 },
  { type: 4, comment: "I can't stop watching!", score: 14 },
  { type: 0, comment: "Awesome content!", score: 24 },
  { type: 0, comment: "I can't stop watching!", score: 12 },
  { type: 0, comment: "This deserves more views!", score: 60 },
  { type: 0, comment: "Great video!", score: 76 },
  { type: 2, comment: "I learned a lot!", score: 63 },
  { type: 0, comment: "I learned a lot!", score: 58 },
  { type: 0, comment: "You're the best!", score: 94 },
  { type: 2, comment: "This is amazing!", score: 34 },
  { type: 2, comment: "Awesome content!", score: 98 },
  { type: 4, comment: "Great video!", score: 7 },
  { type: 4, comment: "Awesome content!", score: 35 },
  { type: 2, comment: "This deserves more views!", score: 16 },
  { type: 4, comment: "This deserves more views!", score: 78 },
  { type: 0, comment: "Great video!", score: 99 },
  { type: 0, comment: "You're the best!", score: 62 },
  { type: 4, comment: "I'm subscribing!", score: 60 },
  { type: 0, comment: "Keep up the good work!", score: 6 },
  { type: 4, comment: "Great video!", score: 37 },
  { type: 4, comment: "You're the best!", score: 50 },
  { type: 2, comment: "Great video!", score: 20 },
  { type: 4, comment: "I learned a lot!", score: 94 },
  { type: 0, comment: "I learned a lot!", score: 50 },
  { type: 2, comment: "I learned a lot!", score: 73 },
  { type: 2, comment: "So funny!", score: 41 },
  { type: 0, comment: "I can't stop watching!", score: 62 },
  { type: 4, comment: "This deserves more views!", score: 65 },
  { type: 4, comment: "This is amazing!", score: 0 },
  { type: 4, comment: "I learned a lot!", score: 97 },
  { type: 2, comment: "This is amazing!", score: 80 },
  { type: 2, comment: "I learned a lot!", score: 66 },
  { type: 4, comment: "Keep up the good work!", score: 75 },
  { type: 2, comment: "So funny!", score: 56 },
  { type: 0, comment: "I learned a lot!", score: 63 },
  { type: 0, comment: "Keep up the good work!", score: 54 },
  { type: 4, comment: "I can't stop watching!", score: 62 },
  { type: 0, comment: "You're the best!", score: 63 },
  { type: 0, comment: "So funny!", score: 92 },
  { type: 4, comment: "So funny!", score: 96 },
  { type: 0, comment: "This deserves more views!", score: 78 },
  { type: 4, comment: "So funny!", score: 71 },
  { type: 4, comment: "I can't stop watching!", score: 74 },
  { type: 4, comment: "I learned a lot!", score: 81 },
  { type: 2, comment: "Keep up the good work!", score: 18 },
  { type: 2, comment: "This deserves more views!", score: 33 },
  { type: 0, comment: "I'm subscribing!", score: 39 },
  { type: 4, comment: "I'm subscribing!", score: 66 },
  { type: 2, comment: "This deserves more views!", score: 92 },
  { type: 2, comment: "I learned a lot!", score: 57 },
  { type: 0, comment: "I'm subscribing!", score: 4 },
  { type: 0, comment: "I learned a lot!", score: 73 },
  { type: 0, comment: "You're the best!", score: 72 },
  { type: 0, comment: "Great video!", score: 65 },
  { type: 0, comment: "Awesome content!", score: 77 },
  { type: 2, comment: "So funny!", score: 51 },
  { type: 0, comment: "Keep up the good work!", score: 34 },
  { type: 4, comment: "I'm subscribing!", score: 88 },
  { type: 4, comment: "This deserves more views!", score: 14 },
  { type: 0, comment: "Awesome content!", score: 39 },
  { type: 2, comment: "I'm subscribing!", score: 55 },
  { type: 2, comment: "Awesome content!", score: 30 },
  { type: 2, comment: "You're the best!", score: 85 },
  { type: 2, comment: "This deserves more views!", score: 46 },
  { type: 4, comment: "This deserves more views!", score: 36 },
  { type: 2, comment: "Awesome content!", score: 58 },
  { type: 4, comment: "I can't stop watching!", score: 53 },
  { type: 4, comment: "Great video!", score: 60 },
  { type: 4, comment: "I learned a lot!", score: 28 },
  { type: 2, comment: "I learned a lot!", score: 45 },
  { type: 0, comment: "You're the best!", score: 96 },
  { type: 4, comment: "Great video!", score: 59 },
  { type: 4, comment: "I'm subscribing!", score: 69 },
  { type: 2, comment: "Keep up the good work!", score: 14 },
  { type: 4, comment: "So funny!", score: 16 },
  { type: 4, comment: "You're the best!", score: 47 },
  { type: 0, comment: "This deserves more views!", score: 62 },
  { type: 4, comment: "Great video!", score: 28 },
  { type: 4, comment: "This deserves more views!", score: 15 },
  { type: 0, comment: "I learned a lot!", score: 76 },
  { type: 0, comment: "I'm subscribing!", score: 19 },
  { type: 0, comment: "I'm subscribing!", score: 12 },
  { type: 0, comment: "I can't stop watching!", score: 30 },
  { type: 2, comment: "I can't stop watching!", score: 33 },
  { type: 0, comment: "I learned a lot!", score: 43 },
  { type: 2, comment: "This is amazing!", score: 55 },
  { type: 4, comment: "I learned a lot!", score: 43 },
  { type: 2, comment: "This is amazing!", score: 35 },
  { type: 0, comment: "Keep up the good work!", score: 86 },
  { type: 4, comment: "Awesome content!", score: 95 },
  { type: 0, comment: "So funny!", score: 63 },
  { type: 4, comment: "So funny!", score: 36 },
  { type: 0, comment: "I can't stop watching!", score: 47 },
  { type: 0, comment: "Keep up the good work!", score: 44 },
  { type: 4, comment: "Keep up the good work!", score: 47 },
  { type: 4, comment: "I'm subscribing!", score: 88 },
  { type: 2, comment: "I learned a lot!", score: 48 },
  { type: 2, comment: "You're the best!", score: 65 },
  { type: 4, comment: "You're the best!", score: 100 },
  { type: 4, comment: "So funny!", score: 14 },
  { type: 2, comment: "Keep up the good work!", score: 50 },
  { type: 4, comment: "Keep up the good work!", score: 80 },
  { type: 2, comment: "I can't stop watching!", score: 77 },
  { type: 0, comment: "This is amazing!", score: 53 },
  { type: 4, comment: "You're the best!", score: 57 },
  { type: 4, comment: "So funny!", score: 78 },
  { type: 2, comment: "I can't stop watching!", score: 55 },
  { type: 2, comment: "This is amazing!", score: 90 },
  { type: 4, comment: "Keep up the good work!", score: 42 },
  { type: 4, comment: "This is amazing!", score: 22 },
  { type: 2, comment: "This is amazing!", score: 50 },
  { type: 2, comment: "Keep up the good work!", score: 78 },
  { type: 0, comment: "You're the best!", score: 71 },
  { type: 0, comment: "Keep up the good work!", score: 62 },
  { type: 2, comment: "You're the best!", score: 38 },
  { type: 0, comment: "You're the best!", score: 91 },
  { type: 2, comment: "Awesome content!", score: 10 },
  { type: 2, comment: "You're the best!", score: 93 },
  { type: 4, comment: "Awesome content!", score: 5 },
  { type: 2, comment: "You're the best!", score: 42 },
  { type: 0, comment: "This deserves more views!", score: 41 },
  { type: 2, comment: "I learned a lot!", score: 91 },
  { type: 4, comment: "Keep up the good work!", score: 4 },
  { type: 4, comment: "So funny!", score: 2 },
  { type: 4, comment: "I'm subscribing!", score: 74 },
  { type: 2, comment: "Awesome content!", score: 49 },
  { type: 2, comment: "Great video!", score: 3 },
  { type: 0, comment: "Great video!", score: 80 },
  { type: 2, comment: "So funny!", score: 0 },
  { type: 2, comment: "I'm subscribing!", score: 12 },
  { type: 0, comment: "You're the best!", score: 2 },
  { type: 2, comment: "This is amazing!", score: 83 },
  { type: 4, comment: "Great video!", score: 40 },
  { type: 0, comment: "I can't stop watching!", score: 65 },
  { type: 0, comment: "Keep up the good work!", score: 56 },
  { type: 2, comment: "You're the best!", score: 20 },
  { type: 0, comment: "Awesome content!", score: 12 },
  { type: 0, comment: "I learned a lot!", score: 72 },
  { type: 2, comment: "This deserves more views!", score: 68 },
  { type: 4, comment: "You're the best!", score: 70 },
  { type: 2, comment: "So funny!", score: 73 },
  { type: 0, comment: "You're the best!", score: 88 },
  { type: 2, comment: "Awesome content!", score: 21 },
  { type: 4, comment: "I can't stop watching!", score: 57 },
  { type: 4, comment: "I learned a lot!", score: 82 },
  { type: 2, comment: "You're the best!", score: 48 },
  { type: 2, comment: "This deserves more views!", score: 80 },
  { type: 0, comment: "Great video!", score: 38 },
  { type: 2, comment: "So funny!", score: 3 },
  { type: 0, comment: "I learned a lot!", score: 91 },
  { type: 4, comment: "Keep up the good work!", score: 27 },
  { type: 2, comment: "This deserves more views!", score: 52 },
  { type: 4, comment: "Keep up the good work!", score: 93 },
  { type: 0, comment: "This is amazing!", score: 31 },
  { type: 2, comment: "This deserves more views!", score: 15 },
  { type: 4, comment: "This deserves more views!", score: 57 },
  { type: 4, comment: "Great video!", score: 42 },
  { type: 0, comment: "This is amazing!", score: 9 },
  { type: 4, comment: "I learned a lot!", score: 64 },
  { type: 2, comment: "This is amazing!", score: 13 },
  { type: 2, comment: "So funny!", score: 82 },
  { type: 2, comment: "You're the best!", score: 11 },
  { type: 2, comment: "Awesome content!", score: 16 },
  { type: 0, comment: "You're the best!", score: 53 },
  { type: 0, comment: "So funny!", score: 18 },
  { type: 2, comment: "I learned a lot!", score: 82 },
  { type: 2, comment: "I learned a lot!", score: 51 },
  { type: 0, comment: "I learned a lot!", score: 93 },
  { type: 0, comment: "You're the best!", score: 62 },
  { type: 4, comment: "So funny!", score: 28 },
  { type: 2, comment: "So funny!", score: 4 },
  { type: 0, comment: "I'm subscribing!", score: 71 },
  { type: 4, comment: "So funny!", score: 94 },
  { type: 2, comment: "Awesome content!", score: 35 },
  { type: 4, comment: "You're the best!", score: 53 },
  { type: 4, comment: "So funny!", score: 56 },
  { type: 0, comment: "Great video!", score: 0 },
  { type: 2, comment: "Great video!", score: 95 },
  { type: 0, comment: "I can't stop watching!", score: 71 },
  { type: 2, comment: "This deserves more views!", score: 46 },
  { type: 4, comment: "Great video!", score: 71 },
];
